version: '3.6'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    command: redis-server

  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300:11300
    volumes:
      - beanstalkd:/mnt/ddev_config

volumes:
  redis:
    driver: local
  beanstalkd:
    driver: local
